### ISSUE TITLE
java.lang.IllegalStateException in "VersionedEntityStorageOnStorage.<init>", Version 1.5.1

### ISSUE THREAD

**Issue by Nanduhirion** [JaneWardSandy/eclipse-pde-partial-idea#100]
java.lang.IllegalStateException: storage must be immutable, but got: com.intellij.workspaceModel.storage.impl.MutableEntityStorageImpl
	at com.intellij.workspaceModel.storage.impl.VersionedEntityStorageOnStorage.<init>(VersionedEntityStorageImpl.kt:96)
	at com.intellij.packaging.impl.artifacts.workspacemodel.PackagingElementInitializer.initialize(PackagingElementInitializer.kt:14)
	at com.intellij.packaging.elements.CompositePackagingElement.lambda$addOrFindChild$1(CompositePackagingElement.java:36)
	at java.base/java.util.Objects.requireNonNullElseGet(Objects.java:308)
	at com.intellij.packaging.elements.CompositePackagingElement.lambda$addOrFindChild$2(CompositePackagingElement.java:36)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1783)
	at com.intellij.packaging.elements.CompositePackagingElement.lambda$addOrFindChild$4(CompositePackagingElement.java:33)
	at com.intellij.packaging.elements.PackagingElement.update(PackagingElement.java:144)
	at com.intellij.packaging.elements.CompositePackagingElement.addOrFindChild(CompositePackagingElement.java:28)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.setCompileArtifact(ModuleHelper.kt:116)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.setCompileArtifact(ModuleHelper.kt:77)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.setCompileArtifact$default(ModuleHelper.kt:66)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.resetCompileArtifact(ModuleHelper.kt:63)
	at cn.varsa.idea.pde.partial.plugin.config.BundleManagementService$onFinished$1$1.resolve(BundleManagementService.kt:133)
	at cn.varsa.idea.pde.partial.plugin.support.BackgroundResolvable$backgroundResolve$6.run(BackgroundResolvable.kt:25)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by JaneWardSandy** [comment]
I can't duplicate the issue how it was occur
Could you please attach the sample?

**Comment by Nanduhirion** [comment]
I don’t know how to replicate that. I have a complex project and these Exceptions sometimes occur. Sometimes not. What strategy can I implement to replicate it?

**Comment by JaneWardSandy** [comment]
This seems to be an error that occurred when we updated the packaging structure of artifacts with the same name as the module.

If it is convenient for you, please take a screenshot of the artifacts and show me the structure at that time when the error is reported.

Looking at the error stack, it should be that other plug-ins created an unmodifiable output layout, and we tried to change it to cause an error.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/15345355/211961057-7b77966e-732e-434c-a7f2-8b681761c6b8.png">

**Comment by Nanduhirion** [comment]
Hi, 

I cannot replicate this exception, it sometimes occurs, sometimes not. I tried closing and reopening IntelliJ and rebuilding the whole project, but no exception so far. I attached the screenshots that you requested, I hope this helps? I will monitor when the exception occurs and will try to remember what caused it, but I cannot guarantee to catch this error in a certain time frame. Please keep me updated, I will do the same.

Cheers,

Paul


￼


￼

**Comment by JaneWardSandy** [comment]
If this problem does not affect your use for the time being, let's skip it for now.
I'll keep this issue in mind for future development, and try to fix it if I reproduce it.
thanks again
