### ISSUE TITLE
Stacktrace on startup

### ISSUE THREAD

**Issue by demellj** [JaneWardSandy/eclipse-pde-partial-idea#102]
Hi, I seem to invariably get the following stacktrace on startup. I've seen this for a number of release now, and is reproducible on 1.5.2 as well (with IntellijIDEA 22.3.2 community edition).  I thought I should report the issue:

```
   java.lang.RuntimeException: Cannot find an entity
	at com.intellij.packaging.elements.PackagingElement.getThisEntity(PackagingElement.java:155)
	at com.intellij.packaging.impl.elements.FileOrDirectoryCopyPackagingElement.getMyFilePath(FileOrDirectoryCopyPackagingElement.java:120)
	at com.intellij.packaging.impl.elements.FileOrDirectoryCopyPackagingElement.isEqualTo(FileOrDirectoryCopyPackagingElement.java:58)
	at com.intellij.packaging.impl.elements.FileCopyPackagingElement.isEqualTo(FileCopyPackagingElement.java:72)
	at com.intellij.packaging.elements.CompositePackagingElement.myAddOrFindChild(CompositePackagingElement.java:68)
	at com.intellij.packaging.elements.CompositePackagingElement.lambda$addOrFindChild$0(CompositePackagingElement.java:29)
	at com.intellij.packaging.elements.PackagingElement.update(PackagingElement.java:137)
	at com.intellij.packaging.elements.CompositePackagingElement.addOrFindChild(CompositePackagingElement.java:28)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.setCompileArtifact(ModuleHelper.kt:126)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.setCompileArtifact(ModuleHelper.kt:77)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.setCompileArtifact$default(ModuleHelper.kt:66)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.resetCompileArtifact(ModuleHelper.kt:63)
	at cn.varsa.idea.pde.partial.plugin.config.BundleManagementService$onFinished$1$1.resolve(BundleManagementService.kt:133)
	at cn.varsa.idea.pde.partial.plugin.support.BackgroundResolvable$backgroundResolve$6.run(BackgroundResolvable.kt:25)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
Regards,

**Comment by JaneWardSandy** [comment]
I can't reproduce the problem here, please attach a sample project that can reproduce the error

**Comment by demellj** [comment]
After a more careful investigation, it seems I'm able to reproduce this with any PDE Partial project (including a new empty one), so long as an the "Include in project build" option for an artifact is selected.
You can find this option Project Settings -> Artifacts

**Comment by demellj** [comment]
Actually, disregard the careful investigation bit. It seems I cannot always reproduce it, but once I do it, it persists across IDE restarts. Toggling the "include in project build" flag may have something to do with this, but now I'm not sure.

**Comment by JaneWardSandy** [comment]
> Actually, disregard the careful investigation bit. It seems I cannot always reproduce it, but once I do it, it persists across IDE restarts. Toggling the "include in project build" flag may have something to do with this, but now I'm not sure.

Thank you for the steps you provided to reproduce, and I will try to reproduce and fix the problem as soon as possible.

**Comment by JaneWardSandy** [comment]
@demellj I use `222` and `223` in the development environment, and the local installation environment `222` and `223`. I have tried many times, but I still cannot reproduce this problem.

You try to use the repair tool that comes with IDEA to try to repair it to see if it is IDEA's own problem

<img width="276" alt="image" src="https://user-images.githubusercontent.com/15345355/218308725-16b49914-3978-40d5-8c7a-4a6d8bf32ce5.png">

**Comment by demellj** [comment]
I have tried this. Unfortunately this does not resolve the issue.

**Comment by JaneWardSandy** [comment]
Release v1.6.0 temporarily provides a Workaround to suppress the generation of this error.

https://github.com/JaneWardSandy/eclipse-pde-partial-idea/issues/106#issuecomment-1471302946
