### ISSUE TITLE
Cannot find entity for library with ID LibraryId

### ISSUE THREAD

**Issue by JaneWardSandy** [JaneWardSandy/eclipse-pde-partial-idea#11]
**Describe the bug**
Resolve workspace occur error.

**To Reproduce**
1. Open project
2. Right click project tree
3. Click resolve workspace

**Which version of the library did you use?**
release version: 1.1.1

**Additional context**
java.lang.IllegalStateException: Cannot find entity for library with ID LibraryId(name=Partial: javax.inject, tableId=com.intellij.workspaceModel.storage.bridgeEntities.LibraryTableId$ProjectLibraryTableId@1561fa73)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl$librarySnapshotCached$1.invoke(LibraryBridgeImpl.kt:73)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl$librarySnapshotCached$1.invoke(LibraryBridgeImpl.kt:45)
	at com.intellij.workspaceModel.storage.impl.ValuesCache.cachedValue(VersionedEntityStorageImpl.kt:26)
	at com.intellij.workspaceModel.storage.impl.VersionedEntityStorageImpl.cachedValue(VersionedEntityStorageImpl.kt:149)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl.checkDisposed(LibraryBridgeImpl.kt:146)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl.getLibrarySnapshot$intellij_platform_lang_impl(LibraryBridgeImpl.kt:82)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl.getModifiableModel(LibraryBridgeImpl.kt:97)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl.getModifiableModel(LibraryBridgeImpl.kt:45)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.resetLibrary(ModuleHelper.kt:176)
	at cn.varsa.idea.pde.partial.plugin.config.BundleManagementService$onFinished$1.resolve(BundleManagementService.kt:81)
	at cn.varsa.idea.pde.partial.plugin.support.BackgroundResolvable$backgroundResolve$6.run(BackgroundResolvable.kt:27)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by JaneWardSandy** [comment]
Change target Eclipse to Teamcenter, click OK to resolve target, it will occur.

**Comment by JaneWardSandy** [comment]
Issue will fixed and released in 1.1.2
