### ISSUE TITLE
Unable to get com.teamcenter.rac.util.registry.Package for FQName: org.eclipse.jface.window

### ISSUE THREAD

**Issue by wonsuc** [JaneWardSandy/eclipse-pde-partial-idea#120]
**Describe the bug**
Currently, I'm developing TeamCenter RAC custom plug-in. Original source code is running fine on the Eclipse environment, but after configuring the same source code on IntelliJ via the Eclipse PDE Partial Plugin I get an error. 

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.pmspackaging.handlers.CommonHandler.execute(CommonHandler.java:31)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at com.teamcenter.rac.aifrcp.Application.runApplication(Unknown Source)
	at com.teamcenter.rac.aifrcp.Application.start(Unknown Source)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: java.util.MissingResourceException: Unable to get com.teamcenter.rac.util.registry.Package for FQName: org.eclipse.jface.window
	at com.teamcenter.rac.util.Registry.getNode(Unknown Source)
	at com.teamcenter.rac.util.Registry.loadPackage(Unknown Source)
	at com.teamcenter.rac.util.Registry.<init>(Unknown Source)
	at com.teamcenter.rac.util.Registry.initialize(Unknown Source)
	at com.teamcenter.rac.util.Registry.getRegistry(Unknown Source)
	at com.teamcenter.rac.util.Registry.getRegistry(Unknown Source)
	at com.pmspackaging.commands.documentmanagement.folderclone.AbstractCreateWbsDialog.<init>(AbstractCreateWbsDialog.java:94)
	at com.pmspackaging.commands.documentmanagement.folderclone.impl.KSFolderCloneDialog.<init>(KSFolderCloneDialog.java:84)
	at com.pmspackaging.commands.documentmanagement.folderclone.FolderCloneCommand.<init>(FolderCloneCommand.java:48)
	... 50 more
```

The `org.eclipse.jface` library is correctly configured when I check project structure setting with the name `Partial: org.eclipse.jface-3.15.0.v20181123-1505`.

What am I missing?

**To Reproduce**
The error is thrown when I try to open a custom dialog.

**Expected behavior**
Showing a custom dialog window.

**Which version of the library did you use?**
release version: 1.6.4

**Additional context**
TeamCenter version: 12

**Comment by wonsuc** [comment]
My mistake...  

I resolved it by below steps.  

1. Setting `Target` to `C:\Siemens\TC12\portal` instead of `C:\Siemens\TC12\portal\plugins`.  
2. Executing `genregxml.bat` file in the `C:\Siemens\TC12\portal\registry` folder.
