### ISSUE TITLE
Class in function parameter should be import too

### ISSUE THREAD

**Issue by JaneWardSandy** [JaneWardSandy/eclipse-pde-partial-idea#15]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/15345355/121143062-36212900-c86f-11eb-876a-c475636467bb.png">

**Which version of the library did you use?**
release version: 1.1.1

**Additional context**
ERROR: 15:33:36,247  - TcLogger$IC_PrintStream.logButCheckForException:?
java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/teamcenter/rac/aif/kernel/InterfaceAIFComponent
	at cn.varsa.hnintel.casc.mpp.icm.IcoSearchDialog$Factory$invoke$$inlined$apply$lambda$1.invoke(IcoSearchDialog.kt:77)
	at cn.varsa.hnintel.casc.mpp.icm.IcoSearchDialog$Factory$invoke$$inlined$apply$lambda$1.invoke(IcoSearchDialog.kt:53)
	at cn.varsa.ktsl.eclipse.jface.operation.IRunnableContextKt$runWrapper$1.run(IRunnableContext.kt:12)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: java.lang.ClassNotFoundException: com.teamcenter.rac.aif.kernel.InterfaceAIFComponent
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 4 more

**Comment by JaneWardSandy** [comment]
Check value parameters and return type
Will fix and release 1.1.2
