### ISSUE TITLE
com.intellij.diagnostic.PluginException: encoded string too long

### ISSUE THREAD

**Issue by lppedd** [JaneWardSandy/eclipse-pde-partial-idea#36]
This exception causes infinite indexing.

```
com.intellij.diagnostic.PluginException: encoded string too long: 68772 bytes [Plugin: cn.varsa.idea.eclipse.pde.partial]
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.lambda$getSerializationProblemReporter$7(VfsAwareMapReduceIndex.java:384)
	at com.intellij.util.indexing.impl.ValueSerializationChecker.checkValueSerialization(ValueSerializationChecker.java:35)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:320)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:182)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:47)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:263)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:232)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:55)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:26)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1520)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$23(FileBasedIndexImpl.java:1394)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:638)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1361)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1315)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexOneFileOfJob$5(IndexUpdateRunner.java:267)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:421)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:186)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexOneFileOfJob(IndexUpdateRunner.java:270)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexJobsFairly$4(IndexUpdateRunner.java:210)
	at com.intellij.openapi.progress.impl.ProgressSuspender.executeNonSuspendableSection(ProgressSuspender.java:83)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexJobsFairly(IndexUpdateRunner.java:213)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$doIndexFiles$3(IndexUpdateRunner.java:147)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.UTFDataFormatException: encoded string too long: 68772 bytes
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:364)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
	at cn.varsa.idea.pde.partial.plugin.indexes.BundleManifestIndex$BundleManifestExternalizer.save(BundleManifestIndex.kt:40)
	at cn.varsa.idea.pde.partial.plugin.indexes.BundleManifestIndex$BundleManifestExternalizer.save(BundleManifestIndex.kt:35)
	at com.intellij.util.indexing.impl.ValueSerializationChecker.getValueSerializationProblem(ValueSerializationChecker.java:49)
	at com.intellij.util.indexing.impl.ValueSerializationChecker.checkValueSerialization(ValueSerializationChecker.java:33)
	... 48 more
```

**Comment by lppedd** [comment]
This is a "known" issue with `DataOutputStream`, an old JDK class which uses only two bytes to store the data length.  
A possible solution is using
```
com.intellij.util.io.IOUtil#writeUTF
com.intellij.util.io.IOUtil#readUTF
```

I've tested and it works 😄 
I'd replace every usage just to be sure.

**Comment by JaneWardSandy** [comment]
@lppedd thanks, I replace all `writeUTF` and `readUTF` with `writeString` `readString` which was call IOUtil function.
This issue will fix and release in 1.2.3

**Comment by lppedd** [comment]
@JaneWardSandy are you sure it's a good idea? The plugin is going to depends on the bundled `Kotlin` plugin, which is declared as `optional="true"`, if I'm not mistaken.

**Comment by JaneWardSandy** [comment]
@lppedd my mistake, many function required `kotlin` plugin, I will remove `optional` mark

**Comment by lppedd** [comment]
@JaneWardSandy that's ok 😄 But which functions? It would be cool to not depend on it if possible.

**Comment by JaneWardSandy** [comment]
@lppedd Scattered in 20 files, it’s not worth the effort to remove the dependency.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/15345355/126282927-1daa02f5-fb3f-4e81-a49c-d2aeab4b3c25.png">

**Comment by lppedd** [comment]
@JaneWardSandy probably most of them are imported extension functions.
You would need to understand which ones are required because you're trying to support Kotlin in PDE development, and which ones are simply imported because it was easier that way.
Also beware they tend to refactor the Kotlin plugin quite often.

**Comment by JaneWardSandy** [comment]
@lppedd you'r right, I had already met refactor problem. Upgrade into 211 from 203, it had many alert that method not found.
I will try to remove those functions, and upgrade idea version to require 211.
It will finish in release 1.3.0 (IP3), there may be no action for a short time.

**Comment by lppedd** [comment]
@JaneWardSandy no problem, when you have time.
