### ISSUE TITLE
BundleManifestIndex#readBundleManifest: Slow operations are prohibited on EDT

### ISSUE THREAD

**Issue by lppedd** [JaneWardSandy/eclipse-pde-partial-idea#37]
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:108)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:754)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:244)
	at com.intellij.util.indexing.FileBasedIndexEx.getFileData(FileBasedIndexEx.java:166)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFileData(FileBasedIndexImpl.java:1107)
	at cn.varsa.idea.pde.partial.plugin.indexes.BundleManifestIndex$Companion.readBundleManifest(BundleManifestIndex.kt:19)
	at cn.varsa.idea.pde.partial.plugin.cache.BundleManifestCacheService.getManifest0(BundleManifestCacheService.kt:78)
	at cn.varsa.idea.pde.partial.plugin.cache.BundleManifestCacheService.getManifest$lambda-3(BundleManifestCacheService.kt:65)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at cn.varsa.idea.pde.partial.plugin.support.ActionExtKt.readCompute(ActionExt.kt:7)
	at cn.varsa.idea.pde.partial.plugin.cache.BundleManifestCacheService.getManifest(BundleManifestCacheService.kt:65)
	at cn.varsa.idea.pde.partial.plugin.domain.BundleDefinition.getManifest(BundleDefinition.kt:15)
	at cn.varsa.idea.pde.partial.plugin.domain.BundleDefinition.getBundleSymbolicName(BundleDefinition.kt:17)
	at cn.varsa.idea.pde.partial.plugin.resolver.PdeProjectLibraryResolver.resolve$lambda-28$lambda-10(PdeProjectLibraryResolver.kt:46)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:451)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

IntelliJ IDEA 2021.2 Beta (Ultimate Edition)
Build #IU-212.4746.2, built on July 13, 2021
IntelliJ IDEA EAP User
Expiration date: August 12, 2021
Runtime version: 11.0.11+9-b1504.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 8
Registry: lcd.contrast.value=120, editor.distraction.free.mode=true
Kotlin: 212-1.5.10-release-IJ4746.2

**Comment by lppedd** [comment]
Do not worry about this one for now. It will be shown only on EAPs or when in "internal mode".

**Comment by JaneWardSandy** [comment]
It seems case running in `DispatchThread` when read `indexes` with `read action`, but call `getFileData` request `read action`, so we only can:
- ~no in dispatch thread~, `getFileData` request `read action`
- ~use `NonBlockingReadAction` instead `read action`~, we need call `indexes` and return sync
- not in `internal mode`
- in `write action`

So, as you said, we had no way to change it but exit `internal mode` or `write action`
We will not consider dealing with this problem for the time being
<img width="917" alt="image" src="https://user-images.githubusercontent.com/15345355/126254193-3c75224f-847a-45d4-b325-fda5b993ab90.png">
