### ISSUE TITLE
NullPointerException when Execute the RunConfiguration in both Debug/Run Mode

### ISSUE THREAD

**Issue by wangmingliang-ms** [JaneWardSandy/eclipse-pde-partial-idea#58]
```
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Kotlin: 212-1.5.31-release-546-IJ4638.7
```

I got an error when start the run configuration:
```
Failed to execute debug configuration async

java.lang.NullPointerException
	at cn.varsa.idea.pde.partial.plugin.run.PDETargetRunConfiguration$configServiceDelegate$1.getDataPath(PDETargetRunConfiguration.kt:137)
	at cn.varsa.idea.pde.partial.plugin.run.PDETargetRunConfiguration$PDEApplicationCommandLineState.createJavaParameters(PDETargetRunConfiguration.kt:91)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:44)
	at com.intellij.debugger.impl.GenericDebuggerRunner.createContentDescriptor(GenericDebuggerRunner.java:97)
	at com.intellij.debugger.impl.GenericDebuggerRunner.lambda$doExecuteAsync$3(GenericDebuggerRunner.java:90)
	at com.intellij.execution.target.TargetEnvironmentAwareRunProfileState.lambda$prepareTargetToCommandExecution$0(TargetEnvironmentAwareRunProfileState.java:50)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by JaneWardSandy** [comment]
This is so weird, we had check `project compiler` won't be `null` on `checkConfiguration`
```kotlin 
if (compiler == null) throw RuntimeConfigurationWarning(message("run.local.config.noCompiler", project.name))
```

so it maybe `null` on return `compilerOutputPointer`, but method `getCompilerOutputPointer` on `CompilerProjectExtension` not annotate with `Nullable`, and method `getPresentableUrl` on `VirtualFilePointer` was annotate with `NotNull`.
```kotlin
override val dataPath: File get() = File(compiler!!.compilerOutputPointer.presentableUrl, "partial-runtime")
```

could you please upload a sample project that we can reproduce the problem?
