### ISSUE TITLE
Index out of bounds exception in "find Artifact", in version 1.5.1

### ISSUE THREAD

**Issue by Nanduhirion** [JaneWardSandy/eclipse-pde-partial-idea#99]
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.base/java.util.ArrayList.add(ArrayList.java:455)
	at java.base/java.util.ArrayList.add(ArrayList.java:467)
	at com.intellij.packaging.impl.artifacts.workspacemodel.ArtifactModifiableModelBridge.findArtifact(ArtifactModifiableModelBridge.kt:68)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.setCompileArtifact(ModuleHelper.kt:98)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.setCompileArtifact(ModuleHelper.kt:77)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.setCompileArtifact$default(ModuleHelper.kt:66)
	at cn.varsa.idea.pde.partial.plugin.helper.ModuleHelper.resetCompileArtifact(ModuleHelper.kt:63)
	at cn.varsa.idea.pde.partial.plugin.facet.PDEFacet$initFacet$1.resolve(PDEFacet.kt:30)
	at cn.varsa.idea.pde.partial.plugin.support.BackgroundResolvable$backgroundResolve$6.run(BackgroundResolvable.kt:25)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by JaneWardSandy** [comment]
IDEA Internal exception, won't fix
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/15345355/215379161-7b676634-6440-48bb-b623-1736eb5cb6e7.png">
